### ISSUE TITLE
Replace or add live imagery from OAM

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/opendri-website#1]
Since WP already has leaflet integrated it should be possible to add a dynamic map to [this blog post](https://opendri.org/high-resolution-digital-surface-models-using-drones-for-coastal-communities-in-sao-tome-and-principe/) that sources imagery directly from OpenAerialMap?

https://map.openaerialmap.org/#/6.534889761543803,0.04775463479395396,16/12222322323/591df5e5b0eae7f3b143ffe1?_k=qf2g14

TMS endpoint: https://tiles.openaerialmap.org/591df493e407d700113860ff/0/26c33cb7-621e-4482-9b79-ff3b4ba9d4bf/{z}/{x}/{y}.png

Another option would be to embed the source code from this viewer: https://tiles.openaerialmap.org/591df493e407d700113860ff/0/26c33cb7-621e-4482-9b79-ff3b4ba9d4bf/preview#18/0.04737/6.53445

**Comment by tiagojsag** [comment]
Hi @cgiovando 

I believe Wordpress content editors can already add embedable element to post bodies, and that is perhaps the simplest and most flexible solution to adding 3rd party content to the site. Implementing a specific integration to place open aerial maps on blog posts would achieve the same thing and take a lot more effort.

We do have to look into something similar for the OSMA integration and, if it proves to be simple, we can consider enabling usage of other map providers, but I think our core focus should remain implementing the best possible integration with the OSMA API we are developing.

thanks
