### ISSUE TITLE
Issues with links to News

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/opendri-website#31]
For instance in Tanzania: 
![image](https://user-images.githubusercontent.com/1036189/32193816-d1ae4b68-bd8e-11e7-9e3c-8fa07b16a0dc.png)

On the right, it should be news related to Tanzania. It used to work properly.

**Comment by vdeparday** [comment]
A note, I just realized that this is only the dev website: https://dev-gfdrr-opendri.pantheonsite.io/project/tanzania/ so may not be an issue but just want to makes sure any update from to production won't break the website.

**Comment by ppasq** [comment]
No problem in the production site after update.
