### ISSUE TITLE
News thumbnails are blurry - same pic for banner is not

### ISSUE THREAD

**Issue by gracedoherty** [GFDRR/opendri-website#39]
When uploading a featured image on a post, the photo becomes extremely blurry in the post thumbnail. This did not occur for posts a couple months ago. For example, the Open Cities Africa Kickoff 2018 box on the News page (https://opendri.org/category/news/) shows a very blurry featured image. However when you click on the link to the post, that same image is much more clear when featured again at the top of the page.

Compare this to the older post: A Drone’s Eye View: UAV applications for a resilient Seychelles. There is no resolution issue.

**Comment by ppasq** [comment]
The thumbnail sizes can be changed in WP Dashboard Settings/Media panel. However this issue could be related to #43
