### ISSUE TITLE
Twitter embedded Search timeline has been deprecated

### ISSUE THREAD

**Issue by ppasq** [GFDRR/opendri-website#45]
See: https://twittercommunity.com/t/deprecating-widget-settings/102295

**Comment by ppasq** [comment]
My suggestion is to create a Twitter list in the GFDRR account that can be included in the home page box. Example: https://twitter.com/GFDRR/lists/disaster-risk-management

**Comment by gracedoherty** [comment]
Sure, please add the DRM Twitter list. I'm asking GFDRR to create another one: Open Data for Resilience. Will share once it's up.

**Comment by ppasq** [comment]
Fixed. Please open another issue when you want to update the timeline. Thanks.
