### ISSUE TITLE
Change Twitter Feed List

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/opendri-website#49]
@gracedoherty @ppasq currently the Twitter feed is 100% UNISDR, Dr Justin Sharpe, and PreventionWeb, we should replace with the new list as soon as possible.

**Comment by gracedoherty** [comment]
@ppasq  here is the Twitter list to embed: https://twitter.com/GFDRR/lists/open-data-for-resilience

**Comment by ppasq** [comment]
Fixed.

**Comment by vdeparday** [comment]
New Twitter list is looking much nicer ! Nice job updating that.
