### ISSUE TITLE
Password reset for Wordpress not working

### ISSUE THREAD

**Issue by gracedoherty** [GFDRR/opendri-website#50]
@vdeparday can't log in to his Wordpress account. He's tried resetting the password but never receives the password reset email. We know that it's not a problem of the World Bank spam filter.

**Comment by ppasq** [comment]
Sending via email new credentials.

**Comment by ppasq** [comment]
@vdeparday, is it solved?

**Comment by cgiovando** [comment]
This seems to work now, but emails with password reset go to spam (at least in gmail...). That issue may get solved once we move to an @opendri.org authenticated email account.

![screen shot 2019-02-13 at 21 51 41](https://user-images.githubusercontent.com/10201533/52743313-07b21c80-2fda-11e9-9e38-275f56a83c1e.jpg)
