### ISSUE TITLE
Reroute comments to personal emails

### ISSUE THREAD

**Issue by gracedoherty** [GFDRR/opendri-website#53]
Please set up the WordPress comments ("Feedback") so that any new comments get sent directly to vdeparday@worldbank.org and gdoherty2@worldbank.org. Please also check if there's a way to send these comments without stripping the email addresses from them.

Eventually we will want OpenDRI site comments to be sent to our shared mailbox, but we are still working to get that set up with the Bank (hoping to make it info@opendri.org). As I understand, the feedback is currently routing to opendri@understandrisk.org, but this has two problems. First, we are trying to deactivate this email and replace it with the previously mentioned one. Second, comments sent to this email address are stripped of their contact info, making it difficult to respond. (I don't receive them so I'm unsure whether this is done by WordPress, or by the World Bank email system).

**Comment by gracedoherty** [comment]
An update to above: Actually, we are not receiving emails from the site at all, not even to opendri@understandrisk.org.

**Comment by ppasq** [comment]
The feedback form was not configured to send the comment to any email address. I have just added yours and Vivien's. Please let me know if you have received my test comment.
The comment I've received as a test have an email address to reply to so I think it's probably your server that is stripping some info.

**Comment by gracedoherty** [comment]
Sorry for the delay, I was on vacation. I have not received any test comment. I checked my spam box too...

**Comment by ppasq** [comment]
Just sent another comment for test adding @cgiovando Gmail account to the list.
