### ISSUE TITLE
Link Bangladesh blog post to Bangladesh page

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/opendri-website#55]
https://opendri.org/bangladesh-resilience-data-sharing/

**Comment by cgiovando** [comment]
Blog posts are not linked dynamically to project pages. A manual entry needs to be added to each country page, with a link to the relevant blog posts. See the example below:

![screen shot 2019-02-19 at 18 27 24](https://user-images.githubusercontent.com/10201533/53034795-429dcf80-3474-11e9-90ee-fd6e4cc67fbe.jpg)

Adding semantic relations between blog posts and project pages would require more advanced WP backend configuration, and probably some custom code development.
