### ISSUE TITLE
Switch email sender to opendri.org

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/opendri-website#56]
Already mentioned in #53, we should move to info@opendri.org as the sender account for all notifications/messages from the website.

@vdeparday @gracedoherty let us know once the account has been created by WB IT and is ready to use.

**Comment by gracedoherty** [comment]
We've set up opendri@gfdrr.org. They told us that @opendri.org wasn't possible. 

The opendri@gfdrr.org mailbox is ready. I'll work on making it the email for all relevant "contact us" buttons where I am able.

**Comment by gracedoherty** [comment]
Switched all opendri@understandrisk.org references to opendri@gfdrr.org.
(For Index, submitted pull request)

Locations:
- OpenDRI About page has an email us blurb
- opencitiesproject.org homepage "Contact" button is a mailto:
- opencitiesproject.org homepage has an email us blurb
- index.opendri.org About page has an email us blurb
